### ISSUE TITLE
Nil Safety Error Causes Process Panics

### ISSUE THREAD

**Issue by steve-gray** [harness/ff-golang-server-sdk#158]
https://github.com/harness/ff-golang-server-sdk/commit/5d1c3b7456552782f9672f581f497e609b2e91a1

This change did not pass 2 out of 3 CI quality tests, but was merged and released in the last release. Will panic in some circumstances due to lack of null safety checks. Raised as ticket 63281 internally. 

![image](https://github.com/harness/ff-golang-server-sdk/assets/14563775/827c1435-a41c-4d25-bba5-0b6f141a90cb)

All of the changes in that FFM-11212 are probably subject to the same lack of nil-checking on using the `*` operator to dereference.

**Comment by erdirowlands** [comment]
Hi @steve-gray apologies for this oversight.  As you know, we have released a new version with the fix herehttps://github.com/harness/ff-golang-server-sdk/releases/tag/v0.1.23 and provided your team more info on steps we've taken to ensure we catch regressions like these in the future. 
I'll go ahead and close this issue.
