### ISSUE TITLE
Change Package name for the NewCfClient function.

### ISSUE THREAD

**Issue by davejohnston** [harness/ff-golang-server-sdk#97]
Currently to create a new CfClient we have to import the package 'client'.  And call NewCfClient.   This isn't very go idiomatic.
We probably need to support the API at this stage, but should create a package called `harness` or `flags` and define the NewCfClient in it.    That way when instantiating the client the user would call

```
client := flags.NewCfClient(sdkKey string, options ...ConfigOption)
```

We can have the current NewCfClient call the new one, to maintain backwards compatability i.e.
package client 

```
func NewCfClient(sdkKey string, options ...ConfigOption) (*CfClient, error) {
    return flags.NewCfClient(sdkKey, options)
}
```

**Comment by enver-bisevac** [comment]
What do you think about this `ff := client.New(sdkKey string, options ...ConfigOption)` it doesn require any breaking change just add New function
